---
- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation


- import_playbook: 01_site-setup-workstation.yml
- import_playbook: 02_site-install-isolated-node.yml 
- import_playbook: 03_site-setup-openstack.yml
- import_playbook: 04_site-config-tower.yml
